# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: build and push to Azure Container Registry

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
        description: Environment

jobs:
  build:
    runs-on: 'ubuntu-latest'
    environment: ${{ inputs.ENVIRONMENT }}
    defaults:
      run:
        working-directory: ./file-share-to-blob

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://${{ secrets.REGISTRY_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push container image to container registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.REGISTRY_SERVER }}/file-share-to-blob:latest
        file: Dockerfile

